[build]
  publish = "public"
  command = "npm run build"

[functions]
  directory = "server/functions"
  included_files = [
    "server/models/**",
    "server/functions/controllers/**",
    "server/functions/config/**",
    "server/functions/routes/**"
    
    ]
